INSERT INTO dbo.Categories(Name) VALUES ('ECU tools');
INSERT INTO dbo.Categories(Name) VALUES ('Diagnostic tools');
INSERT INTO dbo.Categories(Name) VALUES ('Misc');
INSERT INTO dbo.Categories(Name) VALUES ('Wires');

INSERT INTO dbo.Products(Name,UniqueName,Manufacturer,Description,ImageUrl,Quantity,Price,OriginalPrice,CategoryId) VALUES ('Kess V2','kess-v2','Alientech','ECU reprogramming tool with broad vehicle coverage','images/productImages/kess.jpg',10,3000,3499,1);
INSERT INTO dbo.Products(Name,UniqueName,Manufacturer,Description,ImageUrl,Quantity,Price,OriginalPrice,CategoryId) VALUES ('Galleto 4','galleto-v1','Singway','Ecu reprogramming tool for beggining workshops','images/productImages/galleto.jpg',3,600,670,1);
INSERT INTO dbo.Products(Name,UniqueName,Manufacturer,Description,ImageUrl,Quantity,Price,OriginalPrice,CategoryId) VALUES ('Soldering Station Weller MS81','weller-soldering','Weller','Great value for price. Transform your soldering experience with Weller MS81','images/productImages/weller.jpg',2,298,298,3);
INSERT INTO dbo.Products(Name,UniqueName,Manufacturer,Description,ImageUrl,Quantity,Price,OriginalPrice,CategoryId) VALUES ('PCF7941AT immo chip','7941-immo','NXP','Original PCF7941AT from NXP','images/productImages/pcf7941at.jpg',53,3,3,3);
INSERT INTO dbo.Products(Name,UniqueName,Manufacturer,Description,ImageUrl,Quantity,Price,OriginalPrice,CategoryId) VALUES ('Auto tuner tool','auto-tuner','Auto Tuner','A broadly universal device, everything you can imagine. ECU reflashing, DTC diagnosis, BMW and Mercedes coding and much more options available with Auto-Tuner!','images/productImages/autotuner.jpg',3,1000,1150,1);
INSERT INTO dbo.Products(Name,UniqueName,Manufacturer,Description,ImageUrl,Quantity,Price,OriginalPrice,CategoryId) VALUES ('Red silicone wire 0.5mm Ø','red-wire','Riga wires','The most flexible and durable wiring solution available right here in our shop! Of course the price is for meter of our finest wire.','images/productImages/redwire.jpg',255,0.5,0.5,4);
INSERT INTO dbo.Products(Name,UniqueName,Manufacturer,Description,ImageUrl,Quantity,Price,OriginalPrice,CategoryId) VALUES ('Blue silicone wire 0.5mm Ø','blue-wire','Riga wires','The most flexible and durable wiring solution available right here in our shop! Of course the price is for meter of our finest wire.','images/productImages/bluewire.jpg',255,0.5,0.5,4);
INSERT INTO dbo.Products(Name,UniqueName,Manufacturer,Description,ImageUrl,Quantity,Price,OriginalPrice,CategoryId) VALUES ('Purple silicone wire 0.5mm Ø','purple-wire','Riga wires','The most flexible and durable wiring solution available right here in our shop! Of course the price is for meter of our finest wire.','images/productImages/purplewire.jpg',255,0.5,0.5,4);
INSERT INTO dbo.Products(Name,UniqueName,Manufacturer,Description,ImageUrl,Quantity,Price,OriginalPrice,CategoryId) VALUES ('Universal Start/Stop button','universal-button','unknown','If your vehicles start/stop button is already worn and visually not appealing anymore, it can be exchanged with this product.','images/productImages/startstop.jpg',7,4,4,3);
INSERT INTO dbo.Products(Name,UniqueName,Manufacturer,Description,ImageUrl,Quantity,Price,OriginalPrice,CategoryId) VALUES ('Opel radio pincodes','opel-pincodes','Dealer','We offer Opel multimedia pincodes from the official data bases.','images/productImages/opelpincodes.png',9999,50,50,3);
INSERT INTO dbo.Products(Name,UniqueName,Manufacturer,Description,ImageUrl,Quantity,Price,OriginalPrice,CategoryId) VALUES ('Multimeter BOSCH','multimeter','Bosch','This multimeter is the ideal tool for voltage, current and other electrical property measurement.','images/productImages/boschmultimeter.jpg',15,13.99,13.99,3);
